### ISSUE TITLE
Standalone svg logo for Knox Cocoa Heads

### ISSUE THREAD

**Issue by alexpawlowski** [knoxcocoa/knoxcocoa-presskit#1]
Good morning,

Could you provide a standalone `svg` of the Cocoa Heads meetup logo to this repo?
Would like to use it for the [knoxdevs](https://github.com/KnoxDevs/knoxdevs-presskit) meetup org chart.

Thanks!

**Comment by wigging** [comment]
Your wish has been granted. See the `knoxdevs.svg` file for a vector logo to use in the KnoxDevs quarterly.  Verify that it works in the presentation slide before I close this issue.

**Comment by alexpawlowski** [comment]
Can it be renamed to `knoxcocoa.svg` since that's what it is. It'll live in the `meetup` folder on the KnoxDevs `press-kit` [repo](https://github.com/KnoxDevs/knoxdevs-presskit)

**Comment by wigging** [comment]
In the knoxcocoa-presskit repo I would prefer to keep the name `knoxdevs.svg` because the name infers (from the point of view of the CocoaHeads group) that the file is used for KnoxDevs stuff.

**Comment by alexpawlowski** [comment]
Ok sounds good.
